### ISSUE TITLE
Dimension.parse visibility

### ISSUE THREAD

**Issue by cranst0n** [typelevel/squants#184] opened 2017-02-07 15:31 UTC
Is there a reason why `Dimension.parse` is marked as `protected`? Asking because I'm in a situation where if it were public, a lot of boilerplate would disappear for me.

**Comment by cquiroz** [comment] 2017-02-07 15:34
I don't see a strong reason why it should be protected. If you have a good reason to make it public we should consider it

**Comment by leifwickland** [comment] 2017-02-07 21:04
Alternatively, you could add a public `def apply(a: Any): Try[A] = parse(a)` to `Dimension` to avoid having two equivalent methods in the public API of the `Dimension` subclasses while providing the uniformity @cranst0n seeks.

**Comment by derekmorr** [comment] 2017-02-07 21:38
leifwickland's suggestion seems the least invasive.

**Comment by leifwickland** [comment] 2017-02-07 21:51
@derekmorr My suggestion probably more invasive since it means updating every subclass of `Dimension` to remove the boilerplate `def apply = parse _` line.

**Comment by derekmorr** [comment] 2017-02-08 03:18
Ah, yeah, you're right. I was thinking in terms of exposing formerly internal methods. It would also break binary compatibility.

I like the idea of removing boilerplate from the `Dimension` sub-classes, but at least during 1.x we should probably make `parse` public.

**Comment by leifwickland** [comment] 2017-02-08 03:22
Friendly reminder: if you make `parse` public, please remember to add a
return type annotation.

**Comment by garyKeorkunian** [comment] 2017-02-14 18:33
The original intent of parse was to be used for initializing quantities with the string (ie, Length("10m").  It is that apply method that was intended to be part of the public API.  The parse method is really a helper function.  As I worked on pre-release version, I was trying to minimize exposing methods publically, that may have been refactored later.

That said, I see no reason that in can't be made public.

**Comment by derekmorr** [comment] 2017-02-14 18:56
My concern with making `parse()` public is that I think parse needs some work. We ran into a bug over the weekend where the docs were wrong regarding parsing tuples ( #198 ). I sketched out some proposals to rework `parse()` to use the numeric typeclass, but that wasn't possible without breaking compatibility.

OTOH, since we already fixed the bug, and we can't change the API until 2.x, maybe we should just make it public.

**Comment by cquiroz** [comment] 2017-02-14 21:32
I guess minimizing the public API is a good goal, as you say it makes it easier not to break source compatibility

**Comment by derekmorr** [comment] 2017-03-01 12:11
I'm going to close this. pureconfig-squants was released without it, and we didn't merge it for 1.2.0.

**Closed by derekmorr** 2017-03-01 12:11 UTC

**Comment by cquiroz** [comment] 2017-03-01 12:56
👍
